name: Stock Monitor Bot

on:
  schedule:
    # Runs every 10 minutes (with offset for better reliability)
    - cron: '2,12,22,32,42,52 * * * *'
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [ main ]  # Also run on code changes for testing

jobs:
  monitor-stock:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevent hanging jobs
    
    # Prevent concurrent runs
    concurrency:
      group: stock-monitor
      cancel-in-progress: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install Playwright browsers
      run: npx playwright install chromium
      
    - name: Run stock monitor
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        PRODUCT_URL: ${{ vars.PRODUCT_URL }}  # Optional: Set in Repository Variables
        GITHUB_ACTIONS: true
        RUN_ID: ${{ github.run_id }}
        RUN_NUMBER: ${{ github.run_number }}
      run: |
        echo "🚀 Starting stock monitor - Run #${{ github.run_number }}"
        echo "⏰ Triggered by: ${{ github.event_name }}"
        echo "🕐 Run time: $(date)"
        node monitor.js
      timeout-minutes: 8
      
    - name: Upload logs (if needed)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: monitor-logs
        path: |
          *.log
          logs/
        retention-days: 7 